#theme: jekyll-theme-architect
title: "Learning the Shape: Differential Machine Learning (Risk, 2020)"
email: antoine.savine@deep-analytics.org
description: "Appendices with practical implementation details and extensions"
twitter_username: SavineAntoine
github_username: differential-machine-learning
