#theme: jekyll-theme-architect
title: "Learning the Shape: Differential Machine Learning (Risk, 2020)"
email: antoine.savine@deep-analytics.org
description: "Appendices to the Risk paper: Learning the Shape - Differential Machine Learning, by Brian Huge and Antoine Savine, including mathematical proofs, practical implementation details and extensions"
twitter_username: SavineAntoine
github_username: differential-machine-learning
