#theme: jekyll-theme-architect
title: "Differential Machine Learning (2020)"
email: differential.ml@deep-analytics.org
description: "Appendices to the working paper: Differential Machine Learning, by Brian Huge and Antoine Savine, including mathematical proofs, practical implementation details and extensions"
twitter_username: SavineAntoine
github_username: differential-machine-learning
